version: "2.1"

services:
  api:
    build: .
    command: npm start
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mongo
    expose:
      - "27017"
    command: "--smallfiles --logpath=/dev/null"
    volumes:
      - ./data/mongo:/data/db
